### ISSUE TITLE
Batch detrend

### ISSUE THREAD

**Issue by tdbjacobs** [ContactEngineering/ce-ui#60]
Request: Add detrending to the Batch Edit tool. 
Rationale: It's very common to dump in a whole bunch of measurements taken with the same tool/conditions and therefore, the detrend will be the same for all. 

<Sorry if I've submitted this request before --- I searched but couldn't find it.>

**Comment by pastewka** [comment]
This is already possible. (Indeed has been possible since the very beginning.)
