### ISSUE TITLE
Add NSF logo (funding section of landing page)

### ISSUE THREAD

**Issue by tdbjacobs** [ContactEngineering/ce-ui#66]
Under “Funding by”, please add the NSF logo next to the ERC and other logos

(I (Tevis) have reported this in several NSF reports and it would look better if their logo was reflected on the landing page.)

**Comment by tdbjacobs** [comment]
@pastewka, this is slight high priority because I need to create a Project Outcomes document for one of my grants and wish to include C.E. as a project outcome. I can't do that if we don't have the NSF logo on there.

**Comment by pastewka** [comment]
Should I add a link to the NSF logo?

**Comment by tdbjacobs** [comment]
Yes. Please link to: https://www.nsf.gov<https://www.nsf.gov/>

From: Lars Pastewka ***@***.***>
Date: Sunday, May 12, 2024 at 2:51 PM
To: ContactEngineering/ce-ui ***@***.***>
Cc: Tevis Jacobs ***@***.***>, Author ***@***.***>
Subject: Re: [ContactEngineering/ce-ui] Add NSF logo (funding section of landing page) (Issue #66)

Should I add a link to the NSF logo?
